// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDXzl6ZEP0VV25U-hwAOlOutl-TNesQx_Q",
    authDomain: "minhasfinancasapp-37d3e.firebaseapp.com",
    projectId: "minhasfinancasapp-37d3e",
    storageBucket: "minhasfinancasapp-37d3e.appspot.com",
    messagingSenderId: "915455425980",
    appId: "1:915455425980:web:2375133fd2572977267fb9"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyDXzl6ZEP0VV25U-hwAOlOutl-TNesQx_Q",
    authDomain: "minhasfinancasapp-37d3e.firebaseapp.com",
    projectId: "minhasfinancasapp-37d3e",
    storageBucket: "minhasfinancasapp-37d3e.appspot.com",
    messagingSenderId: "915455425980",
    appId: "1:915455425980:web:2375133fd2572977267fb9"
  );
}
